### PR TITLE
Update sw.Installation.md

### PR DESCRIPTION
**Pull request by jonk4m**
The download link for the standalone zip file of Logic 2 does not seem to be available on the downloads page of Saleae. Please let me know what the link is for the standalone download of Logic 2 with all drivers included.

### CODE REVIEW

**Comment by jonk4m** [comment]
For Clarification, I found the standalone on the Github, but the link included in the support guide does not provide the standalone file.

**Comment by timreyes** [comment]
Sorry about that! I just fixed the support article below:
https://support.saleae.com/logic-software/sw-installation

The link should take you here, which has the standalone download links:
https://support.saleae.com/logic-software/legacy-software/older-software-releases

**Comment by jonk4m** [comment]
Is there a stand-alone download for the 2.x version of Logic? The link you provided second is for the 1.2.29 legacy software.

**Comment by timreyes** [comment]
Unfortunately, there is no standalone version for the Logic 2.x software.

**Comment by Marcus10110** [comment]
@jonk4m did you have any issues using the installer for the 2.x software? We weren't planning on adding a standalone release of Logic 2.x for windows, but we could add if there is enough requests or if there we find new installer errors we can't fix.

Could you add your support for this feature here?
https://ideas.saleae.com/b/feature-requests/widows-standalone-beta-releases

Also, if you're having a problem with the installer, please contact support, and send in any error messages you're seeing.
https://contact.saleae.com/hc/en-us/requests/new

**Pull request closed without merging**
